### ISSUE TITLE
php artisan make:enum throws an error

### ISSUE THREAD

**Issue by GDHub** [nasyrov/laravel-enum#10]
I get this error after installing the plugin and adding it to my Laravel 5.4 project:

[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "make:enum" is not defined.

  Did you mean one of these?
      make:auth
      make:command
      make:controller
      make:event
      make:job
      make:listener
      make:mail
      make:middleware
      make:migration
      make:model
      make:notification
      make:policy
      make:provider
      make:request
      make:seeder
      make:test

**Comment by nasyrov** [comment]
@GDHub I know it might be a late response, but have you tried to update? I've released couple updates.

**Comment by taigfs** [comment]
Hello, I'm experiencing the same error here (Laravel 5.6, PHP 7.2). How do you solve it, @GDHub ?
