### ISSUE TITLE
Two conversion of Enum Value

### ISSUE THREAD

**Issue by ablishek** [nasyrov/laravel-enum#18]
Hi, this may be a silly question, but you convert values to key, but do you also convert key to value?

Example according to documentation:
This is allowed
$status = UserStatusEnum::ACTIVE();

But is there something like this??
$key = 1;
$statusName = UserStatusEnum::Key($key);

Result: 
$statusName => 'ACTIVE'

I need to print the word out, but based on a $key value from the database.

**Comment by mrhn** [comment]
(new UserStatusEnum($key))->getKey();

should solve it?

see [The code for it](https://github.com/nasyrov/laravel-enums/blob/0fd7086561f0506626f85053c151adeca93758a7/src/Enum.php#L67)

**Comment by nasyrov** [comment]
Hi @abhi-cognitivo ,

Sorry for the late reply!

These are the same, and they all return a new enum instance:
```php
$status = UserStatusEnum::ACTIVE();
$status = new UserStatusEnum(UserStatusEnum::ACTIVE);
$status = new UserStatusEnum(10);
```

It's a 'sugar' syntax, you can pick one way or another to work with enums.

To answer your question, say you have a `status` column in your database:

```php
class UserStatusEnum extends Enum {
  const ACTIVE = 10;
  const INACTIVE = 20;

  // get the enum label
  public function label()
  {
    return trans(sprintf('enums.user-status.%s', $this->key));
  }
}

class User extends Model {
  // get the user status label
  public function getStatusAttribute($status)
  {
    return (new UserStatusEnum($status))->label();
  }
}

// echo out the user status label
echo $user->status;

// resources/lang/en/enums.php
return [
  'user-status' => [
    10 => 'Active',
    20 => 'Inactive',
  ]
];
```
Cheers,
Evgenii

**Comment by ablishek** [comment]
Fantastic @nasyrov !
